/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.java;

public class App {
    static Greeter greeter = new Greeter();
    public static void main(String[] args) {
        System.out.println(greeter.getGreeting());
    }
}
